version: 2

models:
  - name: dim_listings_cleansed
    description: Cleansed table which contains Airbnb Listings.
    columns:

    - name: listing_id
      description: Primary key for the Listing
      tests:
      - unique
      - not_null

    - name: host_id
      description: The Host's id. References the Host table.
      tests:
      - not_null
      - relationships:
          to: ref('dim_hosts_cleansed')
          field: host_id
          
    - name: room_type
      description: Type of the apartment / room
      tests:
        - accepted_values:
            values: ['Entire home/apt',
                     'Private room',
                     'Shared room',
                     'Hotel room']
      
    - name: minimum_nights
      description: '{{ doc("dim_listing_cleansed__minimum_nights") }}'
      tests:
        - positive_value

  - name: dim_hosts_cleansed
    description: Cleansed table which contains Airbnb hosts.
    columns:

    - name: host_id
      description: Primary key for the hosts.
      tests:
        - unique
        - relationships:
            to: ref('dim_listings_cleansed')
            field: host_id
      
    - name: host_name
      description: The hosts's name.
      tests:  
        - not_null

    - name: is_superhost
      description: Indicates if a host is a superhost with a t/f statement.
      tests:
        - accepted_values:
            values: ['t','f']

    - name: created_at
      description:  The date a host is created.
      tests: 
        - not_null
        
    - name: updated_at
      description: The date a host is updated.

  - name: dim_listings_w_hosts
    tests:
      - dbt_expectations.expect_table_row_count_to_equal_other_table:
          compare_model: source('airbnb', 'listings')
    columns:
      - name: price
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: number
              #stupid since number is (10,2)
              config:
                severity: warn
          - dbt_expectations.expect_column_quantile_values_to_be_between:
              quantile: .99
              min_value: 50
              max_value: 500
          - dbt_expectations.expect_column_max_to_be_between:
              max_value: 5000
              config:
                severity: warn
                

               